"""Add user code

Revision ID: 43a2b3a4411d
Revises: 2b094ac22935
Create Date: 2017-06-19 19:36:53.232006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a2b3a4411d'
down_revision = '2b094ac22935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('code', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'code')
    # ### end Alembic commands ###
